### PR TITLE
update changelog with latest changes (v8)

### PR DESCRIPTION
**Pull request by JoeChapman**

### CODE REVIEW

**Comment by lennym** [comment]
Are the changelogs always the commit messages of the intervening commits? I shall bear this in mind when writing messages if so.

**Comment by JoeChapman** [comment]
I use the commit messages to describe the changelog message, but not verbatim

**Comment by lennym** [comment]
Super. It will just inform my commit and commit message strategy knowing that. Thanks.

**Comment by JoeChapman** [comment]
Are people happy that the changelog accurately describes the commits?

**Comment by JoeChapman** [comment]
I know it's trivial but @joefitter @lennym @easternbloc can I get an approval please?

**Pull request merged**
